import { defineConfig } from "oxlint";

export default defineConfig({
  options: {
    typeAware: true,
    typeCheck: true,
  },
  rules: {
    "no-throw-literal": "off",
    "prefer-promise-reject-errors": "off",
    "require-await": "off",
    "typescript/await-thenable": "deny",
    "typescript/consistent-return": "deny",
    "typescript/consistent-type-exports": "deny",
    "typescript/dot-notation": "deny",
    "typescript/no-array-delete": "deny",
    "typescript/no-base-to-string": "deny",
    "typescript/no-confusing-void-expression": "deny",
    "typescript/no-deprecated": "deny",
    "typescript/no-duplicate-type-constituents": "deny",
    "typescript/no-floating-promises": "deny",
    "typescript/no-for-in-array": "deny",
    "typescript/no-implied-eval": "deny",
    "typescript/no-meaningless-void-operator": "deny",
    "typescript/no-misused-promises": "deny",
    "typescript/no-misused-spread": "deny",
    "typescript/no-mixed-enums": "deny",
    "typescript/no-redundant-type-constituents": "deny",
    "typescript/no-unnecessary-boolean-literal-compare": "deny",
    "typescript/no-unnecessary-condition": [
      "deny",
      { allowConstantLoopConditions: "only-allowed-literals" },
    ],
    "typescript/no-unnecessary-qualifier": "deny",
    "typescript/no-unnecessary-template-expression": "deny",
    "typescript/no-unnecessary-type-arguments": "deny",
    "typescript/no-unnecessary-type-assertion": "deny",
    "typescript/no-unnecessary-type-conversion": "deny",
    "typescript/no-unnecessary-type-parameters": "deny",
    "typescript/no-unsafe-argument": "deny",
    "typescript/no-unsafe-assignment": "deny",
    "typescript/no-unsafe-call": "deny",
    "typescript/no-unsafe-enum-comparison": "deny",
    "typescript/no-unsafe-member-access": "deny",
    "typescript/no-unsafe-return": "deny",
    "typescript/no-unsafe-type-assertion": "deny",
    "typescript/no-unsafe-unary-minus": "deny",
    "typescript/no-useless-default-assignment": "deny",
    "typescript/non-nullable-type-assertion-style": "deny",
    "typescript/only-throw-error": "deny",
    "typescript/prefer-find": "deny",
    "typescript/prefer-includes": "deny",
    "typescript/prefer-nullish-coalescing": "deny",
    "typescript/prefer-optional-chain": ["deny", { requireNullish: true }],
    "typescript/prefer-promise-reject-errors": "deny",
    "typescript/prefer-readonly": "deny",
    "typescript/prefer-readonly-parameter-types": ["deny", { ignoreInferredTypes: true }],
    "typescript/prefer-reduce-type-parameter": "deny",
    "typescript/prefer-regexp-exec": "deny",
    "typescript/prefer-return-this-type": "deny",
    "typescript/prefer-string-starts-ends-with": "deny",
    "typescript/promise-function-async": "deny",
    "typescript/related-getter-setter-pairs": "deny",
    "typescript/require-array-sort-compare": "deny",
    "typescript/require-await": "deny",
    "typescript/restrict-plus-operands": "deny",
    "typescript/restrict-template-expressions": "deny",
    "typescript/return-await": "deny",
    "typescript/strict-boolean-expressions": "deny",
    "typescript/strict-void-return": "deny",
    "typescript/switch-exhaustiveness-check": "deny",
    "typescript/unbound-method": "deny",
    "typescript/use-unknown-in-catch-callback-variable": "deny",
  },
});
