catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9

overrides:
  vite: "catalog:"
  "@changesets/git": 3.0.4

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
